---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.18.12

platforms:
  - name: centos-6.6
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: device_auth
    run_list:
      - recipe[pertino_client_test_device_auth]
    attributes:

  - name: user_auth
    run_list:
      - recipe[pertino_client_test_user_auth]
    attributes:
