---
driver:
  name: docker
  privileged: true # needed in order to create tunnels
  disable_upstart: false
  run_command: /sbin/init
  ssh_timeout: 15 # until Transport refactor is solved. See: http://git.io/NX70
  ssh_retries: 5

platforms:
  # TODO: Figure out service runner inside a container
  # - name: centos-6.6
  #   driver:
  #     platform: centos
  #     image: centos:6.6

  - name: ubuntu-12.04
    driver:
      platform: ubuntu
      image: ubuntu-upstart:12.04

  - name: ubuntu-14.04
    driver:
      platform: ubuntu
      image: ubuntu-upstart:14.04
